#!/bin/bash
APP_PATH="."
MODULE_PATH="$APP_PATH/module"
MODULE_BASIC="$MODULE_PATH/basic.sh"
MODULE_SECURITY="$MODULE_PATH/security.sh"
MODULE_OPENVPN="$MODULE_PATH/openvpn.sh"
. $MODULE_BASIC
. $MODULE_SECURITY
. $MODULE_OPENVPN

# eth0
WANETH=eth0
# eth1
LOCALETH=eth1
# 255.255.255.0
LOCALNET_MASK=255.255.255.0
# 192.168.0.1
LOCALNET_ADDR=192.168.0.1

#basic $WANETH $LOCALETH $LOCALNET_MASK $LOCALNET_ADDR

#security_syncookies
#security_ping
#security_sourcerouted

VPNETH=tap0
VPNNET=10.0.0.1/24
VPNPORT=6001
VPNPROTO=udp
#openvpn $WANETH $VPNETH $VPNNET $VPNPORT $VPNPROTO
LISTFILE=/root/list.txt
#openvpn_filter $LISTFILE $VPNPROTO
